# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.
# require 'rake'/
require 'pact/tasks'
# require 'rspec/core/rake_task'
# RSpec::Core::RakeTask.new(:spec)
require_relative 'config/application'

task :default => 'pact:verify'
# task :default => [:spec]

# Rails.application.load_tasks
